spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_user
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8881
#paging
pageable:
  page:
    size: 10
    number: 1
    sortBy: name
    sortType: desc
